name: CD

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push production image
        uses: docker/build-push-action@v6
        with:
          context: ./packages/server
          file: ./packages/server/Dockerfile
          push: false
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache

  deploy-frontend:
    name: Deploy Frontend to Vercel
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install frontend dependencies
        working-directory: packages/client
        run: npm ci

      - name: Build frontend
        working-directory: packages/client
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          working-directory: packages/client
          vercel-project-path: ./packages/client

  smoke-test:
    name: Smoke Test Deployment Front
    needs: deploy-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check home page is reachable
        run: |
          URL="https://todos-client-server-kappa.vercel.app/"
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" "$URL")

          echo "Status code: $STATUS"

          if [ "$STATUS" -ne 200 ]; then
            echo "Smoke test failed: site not reachable"
            exit 1
          fi

          echo "Smoke test passed"

  deploy-backend:
    name: Deploy Backend to Render
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}&imgURL=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:${{ github.ref_name }}"

  smoke-test-backend:
    name: Smoke Test Deployment Backend
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Check backend API is reachable
        run: |
          URL="https://todo-backend-r4qh.onrender.com/"
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" "$URL")

          echo "Status code: $STATUS"

          if [ "$STATUS" -ne 200 ]; then
            echo "Smoke test failed: backend not reachable"
            exit 1
          fi

          echo "Smoke test backend passed"        
