name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

  lint-commits:
    name: Lint PR commits
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Commitlint
        run: npm install --save-dev @commitlint/cli @commitlint/config-conventional

      - name: Lint commits of PR
        run: npx commitlint --from origin/main --to HEAD

  security-scan-npm:
    name: Security Scan (npm audit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # backend
      - name: Install backend dependencies
        working-directory: ./packages/server
        run: npm install

      - name: NPM Audit backend
        working-directory: ./packages/server
        run: npm audit --audit-level=high

      # frontend
      - name: Install frontend dependencies
        working-directory: ./packages/client
        run: npm install

      - name: NPM Audit frontend
        working-directory: ./packages/client
        run: npm audit --audit-level=high

  test:
    runs-on: ubuntu-latest
    needs: lint-commits
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install
        working-directory: packages/server

      - name: Run tests with coverage
        run: npm run test:coverage
        working-directory: packages/server

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: packages/server/coverage/*


  coverage:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage


      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      #- name: Verify coverage
        #run: |
        #  COV=$(jq '.total.lines.pct' coverage/coverage-summary.json)
        #  COV_INT=${COV%.*}
        #  THRESHOLD=70

        #  echo "Coverage: $COV_INT% (min: $THRESHOLD%)"

        #  if [ "$COV_INT" -lt "$THRESHOLD" ]; then
        #    echo "Coverage too low"
        #    exit 1
        #  fi

        #  echo "Coverage OK"
    
  build-docker:
    name: Build Docker image (for PR scan)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./packages/server
          file: ./packages/server/Dockerfile
          push: false
          load: true
          tags: todo-backend:pr

  security-scan-docker:
    name: Security Scan (Trivy)
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.event_name == 'pull_request'
    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy scan on built image
        run: |
          echo "Scanning Docker image todo-backend..."
          trivy image --exit-code 1 --severity CRITICAL todo-backend:pr

